// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AnimegoorgTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testuppanelbuttons() {
    // Open page https://animego.org/
    driver.get("https://animego.org/");
    // Set window resolution
    driver.manage().window().setSize(new Dimension(1536, 835));
    // Open page https://animego.org/
    driver.findElement(By.cssSelector(".container img")).click();
    // Click the button on the main page up panel "Аниме"
    driver.findElement(By.linkText("Аниме")).click();
    // Click the button on the main page up panel "Манга"
    driver.findElement(By.linkText("Манга")).click();
    // Click the button on the main page up panel "Персонажи"
    driver.findElement(By.linkText("Персонажи")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
    // Click the button on the main page up panel "Случайное аниме"
    driver.findElement(By.linkText("Случайное аниме")).click();
  }
  @Test
  public void testbuttonunderuppanel() {
    // Open page https://animego.org/
    driver.get("https://animego.org/");
    // Set window resolution
    driver.manage().window().setSize(new Dimension(1536, 835));
    // Click the button on the main page under up panel "Онгоинги"
    driver.findElement(By.linkText("Онгоинги")).click();
    // Open page https://animego.org/
    driver.findElement(By.cssSelector(".container img")).click();
    // Click the button on the main page under up panel "2022 год"
    driver.findElement(By.linkText("2022 год")).click();
    // Open page https://animego.org/
    driver.findElement(By.linkText("AnimeGO")).click();
    // Click the button on the main page under up panel "2021 год"
    driver.findElement(By.linkText("2021 год")).click();
    // Open page https://animego.org/
    driver.findElement(By.cssSelector(".container img")).click();
  }
  @Test
  public void animethisseason() {
    // Open page https://animego.org/
    driver.get("https://animego.org/");
    // Set window resolution
    driver.manage().window().setSize(new Dimension(1536, 835));
    // Click the text "Аниме зимнего сезона" on the main page
    driver.findElement(By.linkText("Аниме весеннего сезона")).click();
    // Open page https://animego.org/
    driver.findElement(By.cssSelector(".container img")).click();
    // Click the image anime on the this season anime block
    driver.findElement(By.cssSelector("#tns1-item1 .anime-grid-lazy")).click();
    // Open page https://animego.org/
    driver.findElement(By.cssSelector(".container > .navbar-brand > img")).click();
    // Click the text "Непостижимая Ахарэн" on the main page
    driver.findElement(By.linkText("Непостижимая Ахарэн")).click();
    // Open page https://animego.org/
    driver.findElement(By.cssSelector(".container > .navbar-brand > img")).click();
  }
  @Test
  public void animeupdate() {
    // Open page https://animego.org/
    driver.get("https://animego.org/");
    // Set window resolution
    driver.manage().window().setSize(new Dimension(1536, 835));
    // Click the last update anime on the update anime block
    driver.findElement(By.cssSelector("#slide-toggle-1 > .last-update-item:nth-child(1) .img-square")).click();
    // Open page https://animego.org/
    driver.findElement(By.cssSelector(".container > .navbar-brand > img")).click();
    // Click the under last update anime on the update anime block
    driver.findElement(By.cssSelector("#slide-toggle-1 > .last-update-item:nth-child(2) > .media")).click();
    // Open page https://animego.org/
    driver.findElement(By.cssSelector(".container > .navbar-brand > img")).click();
    // Click the text "Свернуть" on the update anime block "Сегодня"
    driver.findElement(By.cssSelector(".list-group:nth-child(1) > .card-header:nth-child(1) > .bb-dashed-1")).click();
    // Click the text "Свернуть" on the update anime block "Вчера"
    driver.findElement(By.cssSelector(".list-group:nth-child(1) > .card-header:nth-child(3) > .bb-dashed-1")).click();
    // Click the text "Развернуть" on the update anime block "Сегодня"
    driver.findElement(By.cssSelector(".card-header:nth-child(3) > .collapsed")).click();
    // Click the text "Развернуть" on the update anime block "Вчера"
    driver.findElement(By.cssSelector(".collapsed")).click();
  }
  @Test
  public void animeshedule() {
    // Open page https://animego.org/
    driver.get("https://animego.org/");
    // Set window resolution
    driver.manage().window().setSize(new Dimension(1536, 835));
    // Click the text "Развернуть" on the block shedule anime "Понедельник""
    driver.findElement(By.cssSelector(".list-group:nth-child(2) > .card-header:nth-child(1) > .bb-dashed-1")).click();
    // Click the text "Свернуть" on the block shedule anime "Понедельник""
    driver.findElement(By.cssSelector(".list-group:nth-child(2) > .card-header:nth-child(3) > .bb-dashed-1")).click();
    // Click the text "Развернуть" on the block shedule anime "Вторник"
    driver.findElement(By.cssSelector(".list-group:nth-child(2) > .card-header:nth-child(3) > .bb-dashed-1")).click();
    // Click the text "Свернуть" on the block shedule anime "Вторник"
    driver.findElement(By.cssSelector(".card-header:nth-child(5) > .bb-dashed-1")).click();
    // Click the text "Развернуть" on the block shedule anime "Среда"
    driver.findElement(By.cssSelector(".card-header:nth-child(5) > .bb-dashed-1")).click();
    // Click the text "Свернуть" on the block shedule anime "Среда"
    driver.findElement(By.cssSelector(".card-header:nth-child(7) > .bb-dashed-1")).click();
    // Click the text "Развернуть" on the block shedule anime "Четверг"
    driver.findElement(By.cssSelector(".card-header:nth-child(7) > .bb-dashed-1")).click();
    // Click the text "Свернуть" on the block shedule anime "Четверг"
    driver.findElement(By.cssSelector(".card-header:nth-child(9)")).click();
    // Click the text "Развернуть" on the block shedule anime "Пятница"
    driver.findElement(By.cssSelector(".card-header:nth-child(9) > .bb-dashed-1")).click();
    // Click the text "Свернуть" on the block shedule anime "Пятница"
    driver.findElement(By.cssSelector(".card-header:nth-child(9) > .bb-dashed-1")).click();
    // Click the text "Развернуть" on the block shedule anime "Суббота"
    driver.findElement(By.cssSelector(".card-header:nth-child(11) > .bb-dashed-1")).click();
    // Click the text "Свернуть" on the block shedule anime "Суббота"
    driver.findElement(By.cssSelector(".card-header:nth-child(11) > .bb-dashed-1")).click();
    // Click the text "Развернуть" on the block shedule anime "Воскресенье"
    driver.findElement(By.cssSelector(".card-header:nth-child(13) > .bb-dashed-1")).click();
    // Click the text "Свернуть" on the block shedule anime "Воскресенье"
    driver.findElement(By.cssSelector(".card-header:nth-child(13) > .bb-dashed-1")).click();
  }
  @Test
  public void animeresentlyreleased() {
    // Open page https://animego.org/
    driver.get("https://animego.org/");
    // Set window resolution
    driver.manage().window().setSize(new Dimension(1536, 835));
    // Click the text on the block resently released anime "Все"
    driver.findElement(By.linkText("Все")).click();
    // Open page https://animego.org/
    driver.findElement(By.cssSelector(".container img")).click();
    // Click the text on the block resently released anime "Мемуары Ванитаса. Часть 2"
    driver.findElement(By.linkText("Мемуары Ванитаса. Часть 2")).click();
    // Open page https://animego.org/
    driver.findElement(By.cssSelector(".container > .navbar-brand > img")).click();
  }
}
